---
# install backup-restore scripts on target host
- block:
    - name: directory for backup-restore scripts
      file:
        path: /usr/local/bin
        state: directory
        mode: 0755

    - name: install encrypt-decrypt scripts
      copy:
        src: scripts/{{ item }}
        dest: /usr/local/bin/{{ item }}
        owner: root
        mode: 0755
      loop:
        - gz-encrypt.sh
        - gz-decrypt.sh

  # end of block
  become: true
  tags: backup_block_install
...
